apiVersion: 1

contactPoints:
  - orgId: 1
    name: FanFlight Email
    receivers:
      - uid: fanflight-email
        type: email
        settings:
          addresses: "emy.regnapro@gmail.com"
          singleEmail: true
        disableResolveMessage: false

